### ISSUE TITLE
Official GCC present

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/gcc2019#10]
Usual stuff, like a backpack or something Freiburg specific?

`Bächleboot`, produced by the REHA-Verein and useful for playing in the Bächle https://www.reha-verein.de/shop/shop_15.html

**Comment by erxleben** [comment]
- I have asked the reha verein for an offer for 300 pieces Bächle Boot with or without own logo
- additionally I asked them for reusable bags (for bread, fruits etc)

**Comment by bgruening** [comment]
* https://www.laprinta.de/bio-baumwoll-zuziehbeutel?channable=e24485.NjgzLTEyNS0&ref=pla&gclid=CjwKCAjwza_mBRBTEiwASDWVviZmFLW1BbWJtkdgx-TLGIGRTP1tvvT2yefXw4bfhTINq9F248szdxoCOs0QAvD_BwE

* https://www.weltbild.de/artikel/deko-trends/brotbeutel-aus-leinen-2er-set_23869205-1?gclid=CjwKCAjwza_mBRBTEiwASDWVvhRathzvyElkDUswXJkAUjeEL_da0OW3S7UUcZ7E2fV5seYyQnqXBxoCwogQAvD_BwE&origin=pla&wea=8064339

**Comment by bgruening** [comment]
Current favorite, 500, 25x30 and 2 colors:

https://www.laprinta.de/bio-baumwoll-zuziehbeutel?channable=e24485.NjgzLTEyNS0&ref=pla&gclid=CjwKCAjwza_mBRBTEiwASDWVviZmFLW1BbWJtkdgx-TLGIGRTP1tvvT2yefXw4bfhTINq9F248szdxoCOs0QAvD_BwE

**Comment by erxleben** [comment]
https://freiburgcup.de
250 pieces for 3€ each including the lid
contact: Herr Bootz, Tel. 0761/76707721

**Comment by erxleben** [comment]
Update Freiburg Cup: new offer
250 pieces for 1€ per cup plus 0,50€ per lid. I have ordered now 250 cups plus 125 lids. Pick up first week in June.

**Comment by bgruening** [comment]
We have a Brotbag and Freiburg cup now.

* de.NBI pen
* USB stick

**Comment by bgruening** [comment]
![IMG_20190624_125215](https://user-images.githubusercontent.com/469983/60013929-08da1100-9680-11e9-866a-50b50df33ef7.jpg)
