### ISSUE TITLE
Lanyards and badges

### ISSUE THREAD

**Issue by erxleben** [usegalaxy-eu/gcc2019#13]
lanyards including badge from Uni Freiburg:
https://shop.uni-freiburg.de/nocache/Kombipaket+Lanyard+Tickethuelle,nc1557400328,i7.htm
1,61€ for one set; we have 72 left over from Galaxy user conference

**Comment by bebatut** [comment]
What should we put on the badges?

- Name
- Affiliation

Something else?

**Comment by hexylena** [comment]
We should probably put:

- the three topics to talk about

I'm on the fence about putting "instructor" or "speaker".

**Comment by bgruening** [comment]
There are these questions in the registration form "Ask me about ..." which we need to either put there or we to use them in the icebreaker.

**Comment by bebatut** [comment]
Icebreaking: https://github.com/usegalaxy-eu/gcc2019/issues/17

**Comment by erxleben** [comment]
If I do not hear a "no" until Friday (7.7.) from you, I would order 200 more badges of these:
https://shop.uni-freiburg.de/nocache/Kombipaket+Lanyard+Tickethuelle,nc1557400328,i7.htm

1,61€ per badge = 322€

**Comment by erxleben** [comment]
200 Badges for 322€ were ordered today. Will arrive next week.

**Comment by bebatut** [comment]
I will create the badges this week
With @erxleben we thought we could print them ourselves. But maybe on thicker paper. How can we buy thicker paper?

**Comment by bgruening** [comment]
@bebatut please let Monika know. She already has a list of things to order.

**Comment by erxleben** [comment]
Lanyard and badges have arrived

**Comment by bebatut** [comment]
Badges are printed and ready
