### ISSUE TITLE
Icebreaking

### ISSUE THREAD

**Issue by bebatut** [usegalaxy-eu/gcc2019#17]
Should we organize a icebreaking session?
Similar to the one last year (but using the "Ask me about" of the registration): everyone got a paper with several "find someone who..." and a white space for name, they need to fill it before Wednesday evening and we solve them on Thursday to give a small present (Bächlebot?) during the closing session.

What do you think?
@tnabtaf could you share what you used to prepare the icebreaker last year? Thanks a lot

**Comment by tnabtaf** [comment]
@bebatut I was hesitating to do a similar icebreaker this year.  I thought last year's was OK, but was not a stunning success either.  It was also a lot of work.

That said, this year would be less work as [the code already exists](https://github.com/tnabtaf/britnev).  I think using the questions from the registration would be a plus.  However, many of those answers will be unique, making it difficult to find everyone on your list.  (We would need to change the requirements for "winning".)

And I would be strongly in favor of having name labels again.  Without labels, people will just copy the names from other people's forms, or put people's names on without first talking to them (which is the whole point of this - talking to people)

Finally, I like the idea of having lots of winners.

**Comment by heylf** [comment]
I do it.

**Comment by tnabtaf** [comment]
@heylf: I'm working on a composite spreadsheet that unifies all registration information into one set of rows.  However, I won't have it done until next week.

Would that be useful to you?  (I think it would, but it depends on your plans.)

**Comment by heylf** [comment]
Definitely, makes the processing much easier. Thanks a lot!

**Comment by heylf** [comment]
Game has been finished. Printing is on its way.
