### ISSUE TITLE
special post walls

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/gcc2019#20]
* [ ] open positions, prepare one with our open positions
* [ ] Searching  / Offering, prepare also one example, e.g. fix this bug, I offer a cake. Or offer writing this tool, when this datatype is created...
* [ ] Good / Bad things about Galaxy, what do you like and what not. Similar to the Galaxy User Conference. Add one example on each side.
* [ ] 2 walls for the general schedule
  * schedule per day? or for all days?

**Comment by bgruening** [comment]
@bebatut which one is the font which we should use.

**Comment by bebatut** [comment]
We just created:

- What do you like about Galaxy?
- What do you not like about Galaxy?
- Other suggestions for Galaxy?
- For which topic would you like to have a training?
- Job Offers
- BoFs wall
- Any suggestions for next GCC?
- Give & Take: Do you need help? Can you provide help?

**Comment by bebatut** [comment]
Can I close it?
