### ISSUE TITLE
BOF: guided city tour

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/gcc2019#21]
Idea is to offer a guided city tour once or on every day.

https://prospektbestellung.toubiz.de/media/prospekt/file/2370239_FWTM_Stadtfuehrungen_Mai_2019_Assemble.pdf

Price is currently 10€ per person. I will try to get is cheaper.

**Comment by bgruening** [comment]
http://www.festour-gaestefuehrungen.de/freiburgtouren,55294.html

110€ for max 30 people.

**Comment by stephanflemming** [comment]
These ones are quite nice 

http://historix-tours.de/

**Comment by erxleben** [comment]
I can reserve 2.7. at 12-13:15 (during lunch break) or 19:00 in the evening OR/AND on 4.7. at 19:00 
Note: at 19:00 they can not go into the Münster. Visit possible only outside around.

Per tour 30 persons for 130€
http://www.festour-gaestefuehrungen.de/freiburgtouren,55294.html

We should book asap.

**Comment by erxleben** [comment]
City tours were booked and confirmed today.

**Comment by bgruening** [comment]
I added this to our `GCC 2019 Work / Volunteer Slots and Schedule` sheet. We need someone that communicates with the City-Guides and pay them in cash. Bjoern will have money.

Closing this now.
