### ISSUE TITLE
Prepared bullshit bingo?

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/gcc2019#22]
We could prepare a bingo game and put it into the bags. The idea would be to come up with Bingo-Cards that forces people to see talks from different communities. E.g. LC/MS will probably not be mentioned in a genomics session.

I admit creating those cards might be hard, not sure if it's worth the effort.

**Comment by mtekman** [comment]
Each presenter could prepare one in advance and hand them out. 

I forget the rules of the game, but choosing 12-20 words shouldn't be too hard

**Comment by bebatut** [comment]
we could also sample them from the abstracts

**Comment by hexylena** [comment]
Easiest: ask scientific committee members for each track "What are some buzzwords"

**Comment by bgruening** [comment]
We decided to cancel this due to time constraints.
