### ISSUE TITLE
Icecream!!!

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/gcc2019#23]
We are thinking about two solutions here:

* create your own "ice", Apple juice or Coke or ... into an iceform and freeze it. Bjoern will sponsor the forms, but we need a freezer in the Concert house.

* "rent" a Hofeis food truck. They will either come with the truck or provide us with a huge box of ice and a freezer. The latter could be also combined with the first option.

**Comment by erxleben** [comment]
Offer from Hofeis:

To rent an freezer from them, it is 50€ for all days incl. transportation. 
PLUS the icecream cups. Per cup it is 130ml for 1,75€ plus tax

Flavours:
Milcheis:         Vanille, Schokolade, Stracciatella, Haselnuss
Joghurteis:       Joghurt, Joghurt-Heidelbeere
Sorbets:           Erdbeere, Waldbeere, Zitrone

**Comment by bgruening** [comment]
175€ * 3 + 50€ = 575€ for 3 days full of ice. I think this is worth it!

**Comment by bgruening** [comment]
We do take the big-box. This is ~500 ice creams for the 3 days. Bjoern will decide spontaneously if self-made ice is worth the effort.

**Comment by hrhotz** [comment]
I don't want to make it difficult...but maybe we know (based on the dinner registration?) whether we have people with lactose intolerance? will the "sorbets" be suitable for them?

**Comment by bgruening** [comment]
I will have ice made out of juice for those. It that ok?

**Comment by hrhotz** [comment]
Most likely, the "sorbets" should be fine. They should be made just out of juice (https://en.wikipedia.org/wiki/Sorbet)

**Comment by bgruening** [comment]
Ordered, will be delivered on Monday.
