### ISSUE TITLE
online event map

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/gcc2019#3]
Some maps would be nice, with bars, events ...

Like this one for GCC 2018: https://www.google.com/maps/d/edit?mid=1rYNYrnJlS_cogqd1iQOef0BjEeCEjLPx&ll=45.531960055826545%2C-122.64049365&z=13

**Comment by bgruening** [comment]
* beer
* coffee
* icecream
* tourist-places
* Where is the tourist-info.

**Comment by erxleben** [comment]
Link for interacvtive map

https://visit.freiburg.de/freiburg-informieren/uebersichtskarte

**Comment by stephanflemming** [comment]
Here we go

https://drive.google.com/open?id=1zSgA5dc1g9RVafbYFU-arHUtxq8ssCvt&usp=sharing

**Comment by bgruening** [comment]
A few things that are missing:

* our offices, in case of ...
* Schauinsland
* our Krokodil?
* Der Saftladen Maracuja 
* der Biergarten am Seepark

**Comment by bgruening** [comment]
ping @stephanflemming 

@tnabtaf the link could be useful for the mail next week.

**Comment by bebatut** [comment]
we should also link the map to https://bit.ly/gcc2019map (as in the booklet)

**Comment by bgruening** [comment]
Done, can be extended but I think we can close it now.
