### ISSUE TITLE
T-shirt

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/gcc2019#31]
We need to have a T-shirt design. For conference participants and a more general one for helpers.

@MoHeydarian any idea :)

**Comment by bgruening** [comment]
We calculated 15€ currently for one Shirt.

**Comment by bimbam23** [comment]
This company produces good quality for fair prices. Webpage only German.
https://www.wir-machen-druck.de/ 
https://www.wir-machen-druck.de/tshirt-farbig-mit-rundem-halsausschnitt-vorne-hinten-farbig-bedruckt-mit-ihrem-motiv.html#content-view
I would recommend a colored t-shirt with a two sided print. B&C is better than FRUIT-OF-THE-LOOM. If you order 10 - 20+ per size the cost are around 10-12 euros shipping included.
Maybe local shops have the same prices?

**Comment by tnabtaf** [comment]
Last year we just put the conference logo on the front and back - small in front, big in back.  That's a safe fallback.

**Comment by hrhotz** [comment]
just the small conference logo (or the Freiburg Galaxy logo) on the front "my 2¢"

**Comment by bgruening** [comment]
Ordered, let's see if they arrive before the conference ends.
