### ISSUE TITLE
disable job resubmission for GCC

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/gcc2019#35]
Job resubmission can potentially take a lot of resources and are kind of confusing for the user. Since training data should be small, I think we should disable job-resubmission soon and until GCC.

**Comment by bgruening** [comment]
I think this was done. Thanks @erasche!

**Comment by hexylena** [comment]
yes, good catch. xref https://github.com/usegalaxy-eu/infrastructure-playbook/commit/9dac57b2fa772f100b2b7f3f1caee8b9056ff26f
