### ISSUE TITLE
Conference dinner

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/gcc2019#7]
LENZENBERG is cancelled!

I guess we will go to Lenzenberg for the conference dinner: https://www.lenzenberg.de

* reserve Lezenberg
* figure out a deal with the Deutsche Bahn, it is posisble to get a larger train for a certain time
  * to and back Ihringen
* Write a nice prospect on how to reach Lenzenberg
  * by train
  * car
  * train and hike
  * bike
  * add telefon number
* figure out a small bus for people that can not hike up or miss the train
* put Bjoern telefon number on this flyer

**Comment by erxleben** [comment]
We will go to http://www.augustiner-freiburg.de

**Comment by bgruening** [comment]
Testing/Tasting 4.6.19 18:00 at the Augustiner.

**Comment by bgruening** [comment]
Ok, I think this is all setup ... closing.
