### ISSUE TITLE
Hotel reservations/contigents 

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/gcc2019#8]
144 rooms could be reserverd via FWTM, ask @erxleben for more details.

**Comment by erxleben** [comment]
This link can be integrated on the webpage 

(German:)
http://tportal.toubiz.de/freiburgKongresse/ukv/?doSearch=1&ukv_result_order=1&number_adult[]=1&rate=FIT00020070425997179&date_from=29.06.2019&date_to=07.07.2019&reset=1

(English:)
http://tportal.toubiz.de/freiburgKongresse/ukv/?doSearch=1&ukv_result_order=1&number_adult[]=1&rate=FIT00020070425997179&date_from=29.06.2019&date_to=07.07.2019&reset=1&lang=en

**Comment by bgruening** [comment]
I will close this Anika, ok?
