### ISSUE TITLE
Child care options

### ISSUE THREAD

**Issue by erxleben** [usegalaxy-eu/gcc2019#9]
Offer from COGO for 6 days = 3317€
https://drive.google.com/open?id=11SPU8OOn7ey3yyjDvaJHDheM0dJkrN31

Offer from Tagesmutterverein for 6 days = 1749€
https://drive.google.com/open?id=1KQXRS7O3Jwcc2zFTFgUqGiv0yJRjRlGA

**Comment by erxleben** [comment]
I updated the request for child care:
Tagesmutterverein for 4 days, Mon-Thu 1.-4.7.2019
8:30-17:00 per day
2 persons for up to 5 children from 0-6 years
1515,34€
offer see here: https://drive.google.com/open?id=1wQjcYayyPMHZsP_p86IIKGc6_NZyQ_bu

Child care room "Libresso" in Konzerthaus (special price for only child care): 200€+VAT per days (instead of 340€+VAT per day)

Numbers from 10.1.2019

**Comment by bgruening** [comment]
ping @tnabtaf

**Comment by bgruening** [comment]
Childcare is now set and we offer it.
